name: project-deployer
on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: cloning repo
        uses: actions/checkout@v4

      - name: run compose
        run: |
          cd SpeedSolverAPI/
          echo "${{ secrets.ENV_FILE}}" > .env
          docker-compose --env-file .env -f docker/docker-compose.yml --project-directory . up --build -d