name: Deployment

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
      

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Downloading repository
        uses: actions/checkout@v4

      - name: Copy .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run Backend
        run: |
          make build-backend

      - name: Run Frontend
        run: |
          make build-frontend


      