name: Deployment

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
      

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Downloading repository
        uses: actions/checkout@v4

      - name: Copy .env file
        run: |
          echo "${{ secrets.DATABASE_URL }}" > SpeedSolverBackend/SpeedSolverAPI/.env

      - name: Run Backend
        run: |
          make backend

      - name: Run Frontend
        run: |
          make frontend


      